/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lucidchart_aspell_Aspell */

#ifndef _Included_com_lucidchart_aspell_Aspell
#define _Included_com_lucidchart_aspell_Aspell
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lucidchart_aspell_Aspell
 * Method:    init
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_lucidchart_aspell_Aspell_init
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_lucidchart_aspell_Aspell
 * Method:    cleanup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_lucidchart_aspell_Aspell_cleanup
  (JNIEnv *, jobject);

/*
 * Class:     com_lucidchart_aspell_Aspell
 * Method:    check
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_lucidchart_aspell_Aspell_check
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_lucidchart_aspell_Aspell
 * Method:    addUserWords
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_lucidchart_aspell_Aspell_addUserWords
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
